name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install --frozen-lockfile
    
    - name: Run unit tests
      run: bun test
    
    - name: Run integration tests
      run: bun test:integration
      env:
        LENS_ENVIRONMENT: mainnet
    
    - name: Check types
      run: bun run typecheck || echo "No typecheck script found"
    
    - name: Lint code
      run: bunx biome check --write
    
    - name: Test HTTP server startup
      run: |
        timeout 10s bun start:http &
        sleep 5
        curl -f http://localhost:3000/health || exit 1
        pkill -f "bun start:http" || true